#!/bin/bash
# export NNN_PLUG="e:personal/fetch_metadata"

# Description: Push files and folders to Android device via adb
#
# Dependencies: exiftool, mediainfo
#
# Shell: Bash
# Author: Pritam <https://github.com/pritam12426>

# Colors for pretty output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

counter=0

# ───── Get selection or current file ─────
sel="${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}"

# If something is selected in nnn (and .selection is non-empty)
if [ -s "$sel" ]; then
	targets=()
	# Read null-delimited entries (nnn uses \0 as separator)
	while IFS= read -r -d '' i || [ -n "$i" ]; do
		targets+=("$(readlink -f "$i")")
		((counter++))
	done <"$sel"
else
	targets=("$(readlink -f "$1")")
fi

for target in "${targets[@]}"; do
	if [[ -e $target ]]; then
		# echo -e "==> [ About: ${YELLOW}$target${NC} ] <=="

		lower_target=$(printf '%s\n' "$target" | tr '[:upper:]' '[:lower:]')

		case "$lower_target" in
		*.mp3 | *.mp4 | *.mkv | *.avi | *.flac | *.wav | *.mov | *.webm)
			(
				echo -e "==> [ About: ${YELLOW}$target${NC} ] <=="
				mediainfo -f "$target"
			) | less
			;;
		*)
			(
				echo -e "==> [ About: ${YELLOW}$target${NC} ] <=="
				exiftool -sort "$target"
			) | less
			;;
		esac
	fi
done


# Clear selection
if [ -s "$sel" ] && [ -p "$NNN_PIPE" ]; then
	printf "-" >"$NNN_PIPE"
fi
