# This is just an example! Please see available options to customize Navidrome for your needs at

# https://www.navidrome.org/docs/usage/configuration-options/#available-options
# https://www.navidrome.org/docs/usage/configuration-options/

LogLevel = "DEBUG"
Scanner.Schedule = "@every 24h"
TranscodingCacheSize = "150MiB"
MusicFolder = "/Users/pritam/Music/local"

# This is the default path for Homebrew installed ffmpeg

FFmpegPath = "/Users/pritam/.local/bin/ffmpeg"
