# ========================================
# aria2c – XDG-compliant config
# https://man.archlinux.org/man/aria2c.1#OPTIONS
# ========================================

# ---- Basic ----
continue
dir=${HOME}/Downloads/aria2/dow
# input-file=${HOME}/Downloads/aria2/queue.txt
save-session=${HOME}/Downloads/aria2/session
log=${HOME}/.cache/aria2/aria2.log
max-concurrent-downloads=10
max-connection-per-server=10
seed-time=0
seed-ratio=0.0
on-download-complete=exit

# listen-port=60000-60010
# enable-rpc=true
# rpc-secret=${ARIA2_SECRET}

# Default (fast + safe on modern Linux)
file-allocation=falloc

# Do not pre-allocate disk space before downloading begins.
# file-allocation=none
