#!/bin/bash -x
# Auto-generated by binPackageBackup.sh on – 2025-Nov-30
# DO NOT EDIT MANUALLY

set -euo pipefail

bin install "https://github.com/asciinema/asciinema/releases"
bin install "https://github.com/sharkdp/bat"
bin install "https://github.com/charlie0129/batt/releases/tag/v0.6.0"
bin install "https://github.com/tareqimbasher/cargo-seek/releases"
bin install "https://github.com/cointop-sh/cointop"
bin install "https://github.com/terrastruct/d2"
bin install "https://github.com/dandavison/delta"
bin install "https://github.com/ogham/dog"
bin install "https://github.com/mr-karan/doggo"
bin install "https://github.com/Byron/dua-cli/releases"
bin install "https://github.com/sharkdp/fd"
bin install "https://github.com/junegunn/fzf/releases/tag/v0.67.0"
bin install "https://github.com/cli/cli/releases/tag/v2.83.1"
bin install "https://github.com/Orange-OpenSource/hurl"
bin install "https://github.com/Orange-OpenSource/hurl"
bin install "https://github.com/jesseduffield/lazygit"
bin install "https://github.com/gokcehan/lf"
bin install "https://github.com/rclone/rclone"
bin install "https://github.com/BurntSushi/ripgrep"
bin install "https://github.com/astral-sh/ruff/releases/tag/0.14.6"
bin install "https://github.com/go-shiori/shiori"
bin install "https://github.com/skim-rs/skim"
bin install "https://github.com/tamasfe/taplo"
bin install "https://github.com/dduan/tre"
bin install "https://github.com/whyvl/wireproxy"
bin install "https://github.com/ncruces/zenity"
