#!/bin/bash

# === macOS-friendly strict mode ===
set -euo pipefail
IFS=$'\n\t'

# --- Pretty logging to stderr ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { printf "${GREEN}[INFO]${NC}  %s\n" "$*" >&2; }
log_warn() { printf "${YELLOW}[WARN]${NC}  %s\n" "$*" >&2; }
log_error() { printf "${RED}[ERROR]${NC} %s\n" "$*" >&2; }

log_info "Starting bin installer generator (macOS $(uname -m))"

# --- Paths ---
# ===== https://github.com/marcosnils/bin#-configuration =========
# if [[ -x "$BIN_CONFIG" ]]; then
# 	log_info "Using ENV BIN_CONFIG = $BIN_CONFIG"
# 	json_file="$BIN_CONFIG"
# else
# 	log_info "ENV BIN_CONFIG not def"
# 	json_file="${DOT_FILE}/dirwin_os/config/bin/config.json"
# fi

json_file="${HOME}/.config/bin/config.json"
output_file="${DOT_FILE}/dirwin_os/__binPackageInstall.sh"

# --- Prerequisites ---
# 1. Check jq (macOS doesn't have it by default)
if ! command -v jq >/dev/null 2>&1; then
	log_error "jq is not installed!"
	log_error "Install it with: brew install jq"
	exit 1
fi

# 2. Check config file exists and is readable
if [[ ! -f $json_file ]]; then
	log_error "Config file not found: $json_file"
	log_error "Create it or check the path."
	exit 1
fi

if [[ ! -r $json_file ]]; then
	log_error "Config file exists but is not readable: $json_file"
	exit 1
fi

# 3. Ensure output directory exists
output_dir="$(dirname "$output_file")"
if [[ ! -d $output_dir ]]; then
	log_warn "Output directory does not exist, creating: $output_dir"
	mkdir -p "$output_dir"
fi

# --- Generate the installer script ---
log_info "Reading bin URLs from $json_file"
log_info "Writing to $output_file"

{
	echo "#!/bin/bash -x"
	echo "# Auto-generated by $(basename "$0") on – $(date +"%Y-%b-%d")"
	echo "# DO NOT EDIT MANUALLY"
	echo
	echo "set -euo pipefail"
	echo

	# Use bash 3.2-compatible approach: while read with process substitution
	# This reads jq output line-by-line into an array without subshell issues
	urls_count=0
	declare -a urls # Explicitly declare array for older bash
	while IFS= read -r url || [[ -n $url ]]; do
		# Filter out null and empty lines (common with jq)
		[[ $url == "null" || -z $url ]] && continue
		urls[$urls_count]="$url"
		((urls_count++))
	done < <(jq -r '.bins[].url' "$json_file" 2>/dev/null || true)

	if [[ $urls_count -eq 0 ]]; then
		log_warn "No URLs found in '.bins[].url' – check your JSON structure"
		echo "# Warning: No bin URLs found in config"
		echo "# echo 'Nothing to install'"
	else
		log_info "Found $urls_count bin package(s)"
		for url in "${urls[@]}"; do
			printf 'bin install "%s"\n' "$url"
		done
	fi

} >"$output_file"

# Make executable
chmod +x "$output_file" 2>/dev/null || true

# --- Final success message ---
installed_count=$(grep -c '^bin install' "$output_file" 2>/dev/null || echo 0)
log_info "Installer script generated successfully!"
log_info "Output: $output_file"
log_info "Ready to install: $installed_count package(s)"

log_info "Font list backup: ${DOT_FILE}/dirwin_os/__fonts-lists.txt"
find "$HOME/Library/Fonts" -type d -d 1 -exec basename {} \; > "${DOT_FILE}/dirwin_os/__fonts-lists.txt"

exit 0
