#!/bin/bash -x

ln -sf  "$DOT_FILE/config/git/gitconfig"     "$HOME/.gitconfig"
ln -sf  "$DOT_FILE/config.toml"              "$CARGO_HOME/"
ln -sf  "$DOT_FILE/bashrc.bash"              "$HOME/.bashrc"

ln -sf  "$DOT_FILE/config/zsh/zshrc.zsh"     "$HOME/.zshrc"
ln -sf  "$DOT_FILE/config/zsh/zprofile.zsh"  "$HOME/.zprofile"


mkdir  -p "$HOME/.config/"
ln -sf  "$DOT_FILE/config/zsh"              "$HOME/.config/"
ln -sf  "$DOT_FILE/config/aria2"              "$HOME/.config/"
ln -sf  "$DOT_FILE/config/bat"                "$HOME/.config/"
ln -sf  "$DOT_FILE/config/broot"              "$HOME/.config/"
ln -sf  "$DOT_FILE/config/btop"               "$HOME/.config/"
ln -sf  "$DOT_FILE/config/fd"                 "$HOME/.config/"
ln -sf  "$DOT_FILE/config/git"                "$HOME/.config/"
ln -sf  "$DOT_FILE/config/htop"               "$HOME/.config/"
ln -sf  "$DOT_FILE/config/iina-mpv"           "$HOME/.config/"
ln -sf  "$DOT_FILE/config/joshuto"            "$HOME/.config/"
ln -sf  "$DOT_FILE/config/karabiner"          "$HOME/.config/"
ln -sf  "$DOT_FILE/config/lf"                 "$HOME/.config/"
ln -sf  "$DOT_FILE/config/mpv"                "$HOME/.config/"
ln -sf  "$DOT_FILE/config/navidrome"          "$HOME/.config/"
ln -sf  "$DOT_FILE/config/ncdu"               "$HOME/.config/"
ln -sf  "$DOT_FILE/config/npm"                "$HOME/.config/"
ln -sf  "$DOT_FILE/config/nvim"               "$HOME/.config/"
ln -sf  "$DOT_FILE/config/pandoc"             "$HOME/.config/"
ln -sf  "$DOT_FILE/config/radare2"            "$HOME/.config/"
ln -sf  "$DOT_FILE/config/ripgrep"            "$HOME/.config/"
ln -sf  "$DOT_FILE/config/ripgrep"            "$HOME/.config/"
ln -sf  "$DOT_FILE/config/ruff"               "$HOME/.config/"
ln -sf  "$DOT_FILE/config/ruff"               "$HOME/.config/"
ln -sf  "$DOT_FILE/config/taplo"              "$HOME/.config/"
ln -sf  "$DOT_FILE/config/tidy"               "$HOME/.config/"
ln -sf  "$DOT_FILE/config/tig"                "$HOME/.config/"
ln -sf  "$DOT_FILE/config/wireproxy"          "$HOME/.config/"
ln -sf  "$DOT_FILE/config/yt-dlp"             "$HOME/.config/"

mkdir -p "$HOME/.config/zed/"
ln -sf   "$DOT_FILE/config/zed"/snippets       "$HOME/.config/zed/"
ln -sf   "$DOT_FILE/config/zed"/keymap.json    "$HOME/.config/zed/"
ln -sf   "$DOT_FILE/config/zed"/settings.json  "$HOME/.config/zed/"
ln -sf   "$DOT_FILE/config/zed"/zedtasks.json  "$HOME/.config/zed/"


mkdir -p "$HOME/.local/bin"
mkdir -p "$HOME/.local/etc"
mkdir -p "$HOME/.local/share"
ln -sf   "$DOT_FILE/bin/aboutrepo.sh"          "$HOME/.local/bin/aboutrepo"
ln -sf   "$DOT_FILE/bin/comp.sh"               "$HOME/.local/bin/rr"
ln -sf   "$DOT_FILE/bin/create-class.sh"       "$HOME/.local/bin/create-class"
ln -sf   "$DOT_FILE/bin/extractor.sh"          "$HOME/.local/bin/zzz"
ln -sf   "$DOT_FILE/bin/f.sh"                  "$HOME/.local/bin/f"
ln -sf   "$DOT_FILE/bin/ff.py"                 "$HOME/.local/bin/ff"
ln -sf   "$DOT_FILE/bin/fff.py"                "$HOME/.local/bin/fff"
ln -sf   "$DOT_FILE/bin/make-archive.sh"       "$HOME/.local/bin/fff"
ln -sf   "$DOT_FILE/bin/rename_pwd.py"         "$HOME/.local/bin/rrr"
ln -sf   "$DOT_FILE/bin/zed-root.sh"           "$HOME/.local/bin/zed-root"

ln -sf   "$DOT_FILE/global/osm.py"                       "$HOME/.local/bin/osm"
ln -sf   "$DOT_FILE/global/age.py"                       "$HOME/.local/bin/age"


ln -sf "$DOT_FILE/bin/binary/adbtuifm"         "$HOME/.local/bin/"
ln -sf "$DOT_FILE/bin/binary/aria2c"           "$HOME/.local/bin/"
ln -sf "$DOT_FILE/bin/binary/clock"            "$HOME/.local/bin/"
ln -sf "$DOT_FILE/bin/binary/entr"             "$HOME/.local/bin/"
ln -sf "$DOT_FILE/bin/binary/envpath"          "$HOME/.local/bin/"
ln -sf "$DOT_FILE/bin/binary/exiv2"            "$HOME/.local/bin/"
ln -sf "$DOT_FILE/bin/binary/fclones"          "$HOME/.local/bin/"
ln -sf "$DOT_FILE/bin/binary/gsed"             "$HOME/.local/bin/"
ln -sf "$DOT_FILE/bin/binary/htop"             "$HOME/.local/bin/"
ln -sf "$DOT_FILE/bin/binary/live-server"      "$HOME/.local/bin/"
ln -sf "$DOT_FILE/bin/binary/ncdu"             "$HOME/.local/bin/"
# ln -sf "$DOT_FILE/bin/binary/nnn"              "$HOME/.local/bin/"
# ln -sf "$DOT_FILE/bin/binary/nnn-all"          "$HOME/.local/bin/"
ln -sf "$DOT_FILE/bin/binary/pkgconf"          "$HOME/.local/bin/"
ln -sf "$DOT_FILE/bin/binary/pstree"           "$HOME/.local/bin/"
ln -sf "$DOT_FILE/bin/binary/tidy-html"        "$HOME/.local/bin/tidy"
ln -sf "$DOT_FILE/bin/binary/tig"              "$HOME/.local/bin/"
ln -sf "$DOT_FILE/bin/binary/tree"             "$HOME/.local/bin/"
ln -sf "$DOT_FILE/bin/binary/typst-live"       "$HOME/.local/bin/"
ln -sf "$DOT_FILE/bin/binary/vim-htop"         "$HOME/.local/bin/v-htlp"
ln -sf "$DOT_FILE/bin/binary/wget"             "$HOME/.local/bin/"
ln -sf "$DOT_FILE/bin/binary/wget2"            "$HOME/.local/bin/"
ln -sf "$DOT_FILE/bin/binary/xxc-with-c"       "$HOME/.local/bin/xxd"

sudo mkdir -p /usr/local/bin/
sudo ln -sf "$DOT_FILE/bin/binary/ncat"     /usr/local/bin/
sudo ln -sf "$DOT_FILE/bin/binary/ndiff"    /usr/local/bin/
sudo ln -sf "$DOT_FILE/bin/binary/nping"    /usr/local/bin/
sudo ln -sf "$DOT_FILE/bin/binary/nmap"     /usr/local/bin/
